[versions]
core-ktx = "1.12.0"
appcompat = "1.6.1"
material = "1.9.0"
activity-ktx = "1.7.2"
constraintlayout = "2.1.4"
recyclerview = "1.3.2"

[libraries]
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity-ktx" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
